### ISSUE TITLE
JS ERROR ReferenceError: Can't find variable: CodeAttributedString

### ISSUE THREAD

**Issue by asharghi** [shirakaba/nativescript-syntax-highlighter#9]
I tried to use this in my app. Downloaded the folder. Run "npm i" in the folder, and pointing to that folder in my app's packages.json. When i run the app now i get file:///app/nativescript-syntax-highlighter/syntax-highlighter.ts:13:0 JS ERROR ReferenceError: Can't find variable: CodeAttributedString. 

Is it possible to create npm package of this or explain in the readme how to set this up?

**Comment by shirakaba** [comment]
I haven't focused on this repo for a long time, and might be too busy to turn it into an npm package (I'm not expert at making plugins to begin with), but there's an example of how to install it from the GitHub repo given here:

https://github.com/shirakaba/nside#setup

(see the "Setup" section).

The [`CodeAttributedString` type](https://github.com/shirakaba/nativescript-syntax-highlighter/blob/master/src/typings/objc!Highlightr.d.ts) is referenced from the ambient context, so you'll need to add this line to your `references.d.ts`:

```ts
/// <reference path="../node_modules/nativescript-syntax-highlighter/typings/objc!Highlightr.d.ts" />
```

An example of that in the NSIDE project is seen here:

https://github.com/shirakaba/nside/blob/master/app/references.d.ts#L3

**Comment by asharghi** [comment]
Made it work with the guide on the "Setup" section. Great job on making this and thanks for sharing :)
